### PR TITLE
Time bug fix

### LINKED ISSUE #22: Store Time in UTC

### PR DESCRIPTION
**Pull request by 18-F-cali**
closes #22

### CODE REVIEW

**Review by chrisK00 — CHANGES_REQUESTED** [review]
Gj on using private init

File: src/EasyList/ParseAdd.cs [hunk 1]
```diff
@@ -52,13 +52,13 @@ public static class ParseAdd
...
             string? description = positions.ContainsKey("-d") ? GetData("-d", args, positions).ToString() : string.Empty;
-            DateTimeOffset dueDate = positions.ContainsKey("-t") ? DateTimeOffset.Parse(GetData("-t", args, positions).ToString()) : DateTimeOffset.MaxValue;
+            DateTimeOffset? dueDate = positions.ContainsKey("-t") ? DateTimeOffset.Parse(GetData("-t", args, positions).ToString()) : null;
             TodoPriority priority = positions.ContainsKey("-p") ? Enum.Parse<TodoPriority>(GetData("-p", args, positions).ToString().ToUpper()) : TodoPriority.Low;
 
             return new Dictionary<string, string> {
                                                     {"label" ,label },
                                                     {"description",description },
-                                                    {"duedate",dueDate.ToString() },
+                                                    {"duedate",dueDate.ToString() ?? string.Empty },
```
[the remark this answers is not in the document]
Comment (Anequit) [reply src/EasyList/ParseAdd.cs:61]: Despite how clean 1 liners are they can often be confusing to read. Especially if they are long. I recommend doing a classic if statement on line 56.

File: src/EasyList/DataModels/Todo.cs [hunk 2]
```diff
@@ -18,8 +18,19 @@ public class Todo
         public string Label { get; set; }
         public string? Description { get; set; }
         public TodoPriority Priority { get; set; } = TodoPriority.Low;
-        public DateTimeOffset CreatedDate { get; } = DateTimeOffset.Now;
-        public DateTimeOffset? DueDate { get; set;}
+
+        private DateTimeOffset _createdDate;
+        public DateTimeOffset CreatedDate
```
Comment (valincius) [inline src/EasyList/DataModels/Todo.cs:23]:
```suggestion
        private DateTimeOffset _createdDate = DateTimeOffset.UtcNow;
        public DateTimeOffset CreatedDate => _createdDate.ToLocalTime();
```

File: src/EasyList/ParseAdd.cs [hunk 3]
```diff
@@ -50,16 +50,44 @@ public static class ParseAdd
...
+
+            string? description;
+            if (positions.ContainsKey("-d"))
+            {
+                description = GetData("-d", args, positions).ToString();
+            }
+            else
+            {
+                description = string.Empty;
+            }
```
Comment (valincius) [inline src/EasyList/ParseAdd.cs:64]: I think it'd be good to change GetData to return a nullable, then do the following instead of all these if else statements.

`string description = GetData("-d", args, positions)?.ToString() ?? string.Empty;`

Possibly even make `GetData` return a string instead of string builder.

**Review by valincius — APPROVED** [review]

File: src/EasyList.Tests/UnitTest1.cs [hunk 4]
```diff
@@ -0,0 +1,13 @@
+using Xunit;
+
+namespace EasyList.Tests
+{
+    public class UnitTest1
```
Comment (Anequit) [inline src/EasyList.Tests/UnitTest1.cs:5]: This test should be removed as it's not being used.

File: src/EasyList/DataModels/Todo.cs [hunk 5]
```diff
@@ -18,8 +18,16 @@ public class Todo
         public string Label { get; set; }
         public string? Description { get; set; }
         public TodoPriority Priority { get; set; } = TodoPriority.Low;
-        public DateTimeOffset CreatedDate { get; } = DateTimeOffset.Now;
-        public DateTimeOffset? DueDate { get; set;}
+
+        private DateTimeOffset _createdDate = DateTimeOffset.UtcNow;
+        public DateTimeOffset CreatedDate => _createdDate.ToLocalTime();
+       
+        public DateTimeOffset? _dueDate;
```
Comment (Anequit) [inline src/EasyList/DataModels/Todo.cs:25]: _dueDate should be private. All fields prefixed with _ should be private.

**Review by Anequit — CHANGES_REQUESTED** [review]

File: src/EasyList.Tests/UnitTest1.cs (hunk 4 above)
Comment (18-F-cali) [reply src/EasyList.Tests/UnitTest1.cs:5]: I am still learning unit testing, so it haven't implemented it here. This was just the initial stub.
I' ll post the testing code with right commit.

Comment (18-F-cali) [reply src/EasyList.Tests/UnitTest1.cs]: @Anequit Done

**Comment by Anequit** [comment]
Looks good!
